### ISSUE TITLE
Version `1.1.26` was not published

### ISSUE THREAD

**Issue by HofmeisterAn** [cake-contrib/Cake.Sonar#101]
Version `1.1.26` (#99) was not published. The NuGet.org API key is invalid, has expired, or does not have permission to access the specified package. Could you please update the API key?

Build log: https://ci.appveyor.com/project/tomstaijen/cake-sonar/builds/38096202.

**Comment by priorax** [comment]
@tomstaijen , do you know when this will be looked at?
Since this is a secret environment variable (NUGET_API_KEY, https://github.com/cake-contrib/Cake.Sonar/blob/master/build.cake#L117) no one else can update this, however I'm struggling to use this package with newer releases until this is pushed live.

**Comment by tomstaijen** [comment]
A new package was just published.
